package com.agregator.backend.model;

import jakarta.persistence.*; // Import JPA annotations
import java.util.Objects; // Import Objects for hashCode

@Entity // Mark class as a JPA entity (maps to a table named 'category')
public class Category {

    @Id // Mark id as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Use database auto-increment for ID generation
    private Long id;

    @Column(nullable = false, unique = true) // Category names should be non-null and unique
    private String name;

    // Default constructor required by JPA
    public Category() {
    }

    // Constructor without ID (ID generated by database)
    public Category(String name) {
        this.name = name;
    }
    
     // Constructor with ID (useful for testing or specific scenarios)
    public Category(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // Optional: equals, hashCode, toString
    @Override
    public String toString() {
        return "Category{" +
               "id=" + id +
               ", name='" + name + '\'' +
               '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Category category = (Category) o;
        // Use ID for equality if available and non-zero, otherwise compare names
        if (id != null && id != 0 && category.id != null && category.id != 0) {
            return id.equals(category.id);
        }
        return name != null ? name.equals(category.name) : category.name == null;
    }

    @Override
    public int hashCode() {
        // Use ID for hash code if available and non-zero, otherwise use name
         if (id != null && id != 0) {
            return Objects.hash(id);
        }
        return Objects.hash(name);
    }
} 