package com.agregator.backend.model;

import java.util.List;
import java.util.Date;

// DTO representing an approved tool message from Kafka
public class ToolApprovedEvent {

    private String name;
    private String description;
    private String websiteUrl;
    private String affiliateLink;
    private Long categoryId; // ID of the approved category
    private String pricing;
    private List<String> tags;
    private String imageUrl;
    private Integer initialUpvotes; // Optional: approval service might set initial votes
    // Note: The final Tool ID will be generated by this service upon saving.

    // Getters and Setters are needed for Jackson deserialization from Kafka
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    public String getWebsiteUrl() { return websiteUrl; }
    public void setWebsiteUrl(String websiteUrl) { this.websiteUrl = websiteUrl; }
    public String getAffiliateLink() { return affiliateLink; }
    public void setAffiliateLink(String affiliateLink) { this.affiliateLink = affiliateLink; }
    public Long getCategoryId() { return categoryId; }
    public void setCategoryId(Long categoryId) { this.categoryId = categoryId; }
    public String getPricing() { return pricing; }
    public void setPricing(String pricing) { this.pricing = pricing; }
    public List<String> getTags() { return tags; }
    public void setTags(List<String> tags) { this.tags = tags; }
    public String getImageUrl() { return imageUrl; }
    public void setImageUrl(String imageUrl) { this.imageUrl = imageUrl; }
    public Integer getInitialUpvotes() { return initialUpvotes; }
    public void setInitialUpvotes(Integer initialUpvotes) { this.initialUpvotes = initialUpvotes; }
} 