package com.agregator.backend.model;

import jakarta.persistence.*; // Import JPA annotations
import java.util.Date;
import java.util.List;
import java.util.Objects;

@Entity // Mark class as a JPA entity (maps to a table named 'tool')
public class Tool {

    @Id // Mark id as the primary key
    // Using String ID for now based on previous record. Consider Long + @GeneratedValue(strategy = GenerationType.IDENTITY) for auto-incrementing keys
    private String id;

    @Column(nullable = false) // Map name to a non-nullable column
    private String name;

    @Column(length = 1000) // Allow longer description
    private String description;

    private String websiteUrl;
    private String affiliateLink;

    // Many-to-one relationship with Category
    @ManyToOne(fetch = FetchType.EAGER) // Fetch Category eagerly with Tool
    @JoinColumn(name = "category_id", nullable = false) // Foreign key column in 'tool' table
    private Category category;

    private String pricing;

    // For simplicity, storing tags as a comma-separated String. 
    // TODO: Consider a @ManyToMany relationship with a Tag entity for better querying/management.
    private String tags; // Changed from List<String>

    private String imageUrl;
    private Integer upvotes;

    @Temporal(TemporalType.TIMESTAMP) // Map Date to SQL TIMESTAMP
    @Column(nullable = false, updatable = false) // Date added shouldn't change
    private Date dateAdded;

    // --- Constructors ---
    public Tool() {
        // Default constructor required by JPA
    }

    // Constructor for creating new tools (ID might be generated by DB or UUID)
    public Tool(String id, String name, String description, String websiteUrl, String affiliateLink,
                Category category, String pricing, List<String> tags, String imageUrl, Integer upvotes, Date dateAdded) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.websiteUrl = websiteUrl;
        this.affiliateLink = affiliateLink;
        this.category = category;
        this.pricing = pricing;
        // Convert List<String> to comma-separated String for storage
        this.tags = (tags != null && !tags.isEmpty()) ? String.join(",", tags) : null;
        this.imageUrl = imageUrl;
        this.upvotes = upvotes;
        this.dateAdded = dateAdded;
    }

    // --- Getters and Setters (Required by JPA/Frameworks) ---

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getWebsiteUrl() {
        return websiteUrl;
    }

    public void setWebsiteUrl(String websiteUrl) {
        this.websiteUrl = websiteUrl;
    }

    public String getAffiliateLink() {
        return affiliateLink;
    }

    public void setAffiliateLink(String affiliateLink) {
        this.affiliateLink = affiliateLink;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public String getPricing() {
        return pricing;
    }

    public void setPricing(String pricing) {
        this.pricing = pricing;
    }

    // Getter returns String
    public String getTags() {
        return tags;
    }

    // Setter accepts String
    public void setTags(String tags) {
        this.tags = tags;
    }
    
    // Optional: Helper to get tags as List (useful in service/controller)
    public List<String> getTagsAsList() {
        if (this.tags == null || this.tags.trim().isEmpty()) {
            return List.of(); // Return empty list if null/empty
        }
        return List.of(this.tags.split(","));
    }

    // Optional: Helper to set tags from List (useful when creating/updating)
    public void setTagsFromList(List<String> tagsList) {
        this.tags = (tagsList != null && !tagsList.isEmpty()) ? String.join(",", tagsList) : null;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public Integer getUpvotes() {
        return upvotes;
    }

    public void setUpvotes(Integer upvotes) {
        this.upvotes = upvotes;
    }

    public Date getDateAdded() {
        return dateAdded;
    }

    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }

    // --- equals, hashCode, toString (Optional but Recommended) ---
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Tool tool = (Tool) o;
        // Use ID for equality check if it's set, otherwise rely on object identity
        return id != null ? id.equals(tool.id) : super.equals(o);
    }

    @Override
    public int hashCode() {
        // Use ID for hash code if it's set
        return id != null ? Objects.hash(id) : super.hashCode();
    }

    @Override
    public String toString() {
        return "Tool{" +
               "id='" + id + '\'' +
               ", name='" + name + '\'' +
               // ... add other fields if needed for logging
               '}';
    }
} 